In [1]:
import numpy as np

# Input 3x3 matrix
input_mat = np.random.rand(3,3)
print("Input Matrix:\n", input_mat, "\n")

# Kernel 3x3 matrix
kernel = np.random.rand(3,3)
print("Kernel:\n", kernel, "\n")

# (a) Convolution
conv_out = np.sum(input_mat * kernel)
print("Convolution Output:", conv_out, "\n")

# (b) Pooling
max_pool = np.max(input_mat)
min_pool = np.min(input_mat)
print("Max Pooling:", max_pool)
print("Min Pooling:", min_pool, "\n")

# (c) Padding
padded = np.pad(input_mat, ((1,1),(1,1)), mode='constant')
print("Padded Matrix:\n", padded, "\n")

# (d) Activation functions
relu_act = np.maximum(0, input_mat)
sigmoid_act = 1/(1+np.exp(-input_mat))
tanh_act = np.tanh(input_mat)

print("ReLU:\n", relu_act, "\n")
print("Sigmoid:\n", sigmoid_act, "\n")
print("Tanh:\n", tanh_act, "\n")

# (e) Fully connected layer
flat = input_mat.flatten()
fc_w = np.random.rand(9, 4)
fc_out = flat @ fc_w

print("Flattened Input:", flat)
print("Fully Connected Output:\n", fc_out, "\n")

# (f) Global Average Pooling
gap_out = np.mean(input_mat)
print("Global Average Pooling:", gap_out, "\n")

# (g) Dense Layer
dense_w = np.random.rand(9,5)
dense_b = np.random.rand(5)
dense_out = flat @ dense_w + dense_b
print("Dense Layer Output:\n", dense_out, "\n")

# (h) Dropout, BN, Regularization
drop_mask = (np.random.rand(*input_mat.shape) > 0.5).astype(float)
drop_out = input_mat * drop_mask
print("Dropout Mask:\n", drop_mask)
print("Dropout Output:\n", drop_out, "\n")

bn_mean = np.mean(input_mat)
bn_var = np.var(input_mat)
bn_out = (input_mat - bn_mean) / np.sqrt(bn_var + 1e-8)
print("Batch Norm Output:\n", bn_out, "\n")

l1 = np.sum(np.abs(fc_w))
l2 = np.sum(fc_w**2)
print("L1 Regularization Value:", l1)
print("L2 Regularization Value:", l2, "\n")

# (i) Fully connected layers (multiple)
fc_w1 = np.random.rand(9,6)
fc_w2 = np.random.rand(6,3)
multi_fc = (flat @ fc_w1) @ fc_w2
print("Multi-Layer FC Output:\n", multi_fc, "\n")

# (j) Overfitting and underfitting
train_loss = np.array([0.9,0.7,0.5,0.4,0.3,0.35])
val_loss = np.array([0.95,0.8,0.6,0.5,0.55,0.65])

is_overfitting = val_loss[-1] > train_loss[-1]
is_underfitting = train_loss[-1] > 0.4

print("Final Train Loss:", train_loss[-1])
print("Final Val Loss:", val_loss[-1])
print("Overfitting:", is_overfitting)
print("Underfitting:", is_underfitting)


Input Matrix:
 [[0.68723588 0.20753498 0.54661142]
 [0.44258728 0.96953243 0.88540242]
 [0.31137422 0.46729324 0.40773724]] 

Kernel:
 [[0.66245604 0.32090538 0.70622481]
 [0.18923928 0.75963368 0.04438103]
 [0.26149867 0.09505944 0.63376571]] 

Convolution Output: 2.1516871116841947 

Max Pooling: 0.9695324313029456
Min Pooling: 0.20753498409929005 

Padded Matrix:
 [[0.         0.         0.         0.         0.        ]
 [0.         0.68723588 0.20753498 0.54661142 0.        ]
 [0.         0.44258728 0.96953243 0.88540242 0.        ]
 [0.         0.31137422 0.46729324 0.40773724 0.        ]
 [0.         0.         0.         0.         0.        ]] 

ReLU:
 [[0.68723588 0.20753498 0.54661142]
 [0.44258728 0.96953243 0.88540242]
 [0.31137422 0.46729324 0.40773724]] 

Sigmoid:
 [[0.66535175 0.55169832 0.63334906]
 [0.60887536 0.72502629 0.70794048]
 [0.57722066 0.6147429  0.60054519]] 

Tanh:
 [[0.59620334 0.20460587 0.49797623]
 [0.41578674 0.74849875 0.70911547]
 [0.30168676 0.4360